---
x-podman:
  &podman
  init: true
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-hardened: &hardened
  userns_mode: keep-id
  init: true
  security_opt:
    - "label=disable"
    - "no-new-privileges:true"
  cap_drop:
    - ALL

x-logging:
  &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "10m"
    max-file: "3"

volumes:
  hivemind_local_state:
    name: hivemind_local_state
    driver: local
    
services:
  hivemind_listener:
    <<: *hardened
    container_name: hivemind_listener
    hostname: hivemind_listener
    restart: unless-stopped
    image: docker.io/smartgic/hivemind-listener:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      # NOTE: server.conf goes into hivemind-core, identity.json goes into hivemind
      - ${HIVEMIND_CONFIG_FOLDER}:/home/${HIVEMIND_USER}/.config/hivemind:z
      - ${HIVEMIND_CONFIG_FOLDER}:/home/${HIVEMIND_USER}/.config/hivemind-core:z
      - ${HIVEMIND_SHARE_FOLDER}:/home/${HIVEMIND_USER}/.local/share/hivemind:z
      - hivemind_local_state:/home/${HIVEMIND_USER}/.local/state/hivemind

  hivemind_cli:
    <<: *hardened
    container_name: hivemind_cli
    hostname: hivemind_cli
    restart: unless-stopped
    image: docker.io/smartgic/hivemind-cli:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${HIVEMIND_CONFIG_FOLDER}:/home/${HIVEMIND_USER}/.config/hivemind:z
      - ${HIVEMIND_SHARE_FOLDER}:/home/${HIVEMIND_USER}/.local/share/hivemind:z
    depends_on:
      - hivemind_listener
