---
version: "3.9"

x-podman:
  &podman
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-logging:
  &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "200m"
    max-file: "1"

services:
  hivemind_listener:
    <<: *podman
    container_name: hivemind_listener
    hostname: hivemind_listener
    restart: unless-stopped
    image: docker.io/smartgic/hivemind-listener:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${HIVEMIND_CONFIG_FOLDER}:/home/${HIVEMIND_USER}/.config/hivemind:z
      - ${HIVEMIND_SHARE_FOLDER}:/home/${HIVEMIND_USER}/.local/share/hivemind:z

  hivemind_cli:
    <<: *podman
    container_name: ovos_hivemind_cli
    hostname: ovos_hivemind_cli
    restart: unless-stopped
    image: docker.io/smartgic/hivemind-cli:${VERSION}
    logging: *default-logging
    pull_policy: always
    tty: true
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${HIVEMIND_CONFIG_FOLDER}:/home/${HIVEMIND_USER}/.config/hivemind:z
      - ${HIVEMIND_SHARE_FOLDER}:/home/${HIVEMIND_USER}/.local/share/hivemind:z
    depends_on:
      - hivemind_listener
