---
x-podman:
  &podman
  init: true
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-hardened: &hardened
  userns_mode: keep-id
  init: true
  security_opt:
    - "label=disable"
    - "no-new-privileges:true"
  cap_drop:
    - ALL

x-resource-limits: &resource-limits
  deploy:
    resources:
      limits:
        memory: ${STANDARD_MEMORY_LIMIT:-1G}
      reservations:
        memory: 64M

x-light-resource-limits: &light-resource-limits
  deploy:
    resources:
      limits:
        memory: ${LIGHT_MEMORY_LIMIT:-512M}
      reservations:
        memory: 32M

x-logging:
  &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "10m"
    max-file: "3"

services:
  hivemind_webchat:
    <<: [*hardened, *light-resource-limits]
    container_name: hivemind_webchat
    hostname: hivemind_webchat
    restart: unless-stopped
    image: smartgic/hivemind-webchat:${VERSION}
    logging: *default-logging
    pull_policy: always
    environment:
      TZ: $TZ
    ports:
      - "9090:9090"    
